### PR TITLE
Update item-standard.php

### PR DESCRIPTION
**Pull request by switch-cheehau**
Refer to PR aimeos/aimeos-core#245

### CODE REVIEW

**Comment by switch-cheehau** [comment]
Hi Aimeos,

I able to add textarea, but not able to save it. Can you guide me on this?
image

Is `textarea` a suitable keyword?

**Comment by aimeos** [comment]
No, but "text" is: https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Common/Helper/Config/Standard.php#L64-L65

**Comment by switch-cheehau** [comment]
> No, but "text" is: https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Common/Helper/Config/Standard.php#L64-L65

Okay, done.
The next issue is after it saved, new line is missing.

**Comment by aimeos** [comment]
If the configuration has been saved to the database, you should check here why it's not shown again:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/js/admin.js#L343-L428

**Comment by aimeos** [comment]
Input fields are now a textarea by default in 2024.x+

**Pull request closed without merging**
